services:
  database:
    image: mysql:5.7
    tty: true
    command: --innodb-use-native-aio=0 --init-file /data/application/init.sql
    container_name: database
    volumes:
      - ./database:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
    ports:
      - "3306:3306"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3


  api:
    build:
      context: node_api/
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./node_api:/app
    networks:
      - backend
  
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - api
    networks:
      - backend

networks:
  backend:
    driver: bridge